server:
  port: 6999

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8b108.p.ssafy.io:3306/pumg?serverTimezone=Asia/Seoul
    username: root
    password: ehdwns
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        boot: DEBUG
      apache:
        tiles: INFO

